# Generated by Django 3.2 on 2021-05-02 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('account_num', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=30)),
                ('money', models.PositiveIntegerField(default=2000000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post/%Y/%m/')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField(default=0, null=True)),
                ('goal_title', models.CharField(blank=True, max_length=100, null=True)),
                ('goal_diary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_list', to='diary.diary')),
            ],
        ),
    ]
