# Generated by Django 3.2 on 2021-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=30)),
                ('money', models.PositiveIntegerField(default=2000000, null=True)),
            ],
        ),
    ]
